[[redirects]]
from = "/*"
to = "/index.html"
status = 304
force = false

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "/*"
to = "/index.html"
status = 301
force = false